//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int OrderProductsSaleID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OrderProductsSale OrderProductsSale { get; set; }
    }
}
